# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "samiul-test-app-own"
client_id = "3c71a8b1c5e749d271b789d02159cb59"
application_url = "https://zope-mentor-snapshot-premier.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://zope-mentor-snapshot-premier.trycloudflare.com/auth/callback",
  "https://zope-mentor-snapshot-premier.trycloudflare.com/auth/shopify/callback",
  "https://zope-mentor-snapshot-premier.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "samiuls-ext-store.myshopify.com"
